### PR TITLE
fix a couple things

### PR DESCRIPTION
**Pull request by Zambonifofex**
The code was overflowing its container on my screen. Removing the height and width seem to have fixed it.

### CODE REVIEW

**Comment by gavinking** [comment]
I don't like that. With this change the box around the code looks all squashed horizontally.

**Comment by bjansen** [comment]
Perhaps use `max-width` instead of `width`?

**Comment by Zambonifofex** [comment]
@gavinking I don’t think I understand what you mean.

**Comment by FroMage** [comment]
This PR has been closed as a result of moving Ceylon to the Eclipse Foundation, not as a judgement of its value. We are unfortunately unable to restore it ourselves, but if you feel this PR should be reopened, please rebase your work on the current master and create a new PR. Thanks, and sorry for the inconvenience.

**Pull request closed without merging**
