### PR TITLE
Image "Null is not a Duck" to explain optional types in Ceylon vs Java

### PR DESCRIPTION
**Pull request by ge0ffrey**

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
> ```ceylon
if (d exists Duck) {
    d.quack();
}
```

That’s not correct Ceylon code. The correct version would be either `exists d` or `is Duck d`, which both test *and narrow* to `Duck`. The postfix forms `d exists` and `d is Duck` both test the type, but don’t narrow it, so in that case `d.quack()` would still be illegal.

**Comment by ge0ffrey** [comment]
@lucaswerkmeister Fixed.

**Comment by lucaswerkmeister** [comment]
No, `d exists` is not enough. It will test the type at runtime, but not narrow it. Within the `if` block, `d` still has the type `Duck?`. You need to use `exists d`.

**Comment by lucaswerkmeister** [comment]
Yup, now it’s right :)

**Comment by ge0ffrey** [comment]
3th time's a charm?

**Comment by FroMage** [comment]
Thanks, that's a useful diagram, but I'll leave the decision to @gavinking to accept this, as that would be the first diagram we use in our docs.

**Comment by ge0ffrey** [comment]
Yes, of course. I have hundreds of these diagrams in my OptaPlanner docs. A picture says more than a thousands words :) And they get more attention too during diagonal reading.

To make sure the diagrams fit in, I use these conventions:
- Always include the source SVG, so they can be updated easily in the SVG text source (although that requires re-exporting the png bitmap at some point) or with Inkscape (brilliant and easy to use open source SVG editor).
- Only use colors from the tango color palette in Inkscape.
- Always use 600*800 size, so I can reuse them in my slidedeck.

**Comment by ge0ffrey** [comment]
There are a lot of other concepts in the ceylon language, like union types etc that could really benefit from a diagram with some elementary set theory.

**Comment by gavinking** [comment]
Well, thanks @ge0ffrey, but there's three problems with this:

1. The fonts don't match the website (should be Source Sans Pro and Inconsolata).
2. The syntax coloration doesn't match the website theme nor even the IDE theme.
3. The actual size of the image doesn't fit the page (it's too big, should be 630px wide).

So while, in principle this could work as some kind of boxout, but in its current form it's not usable.

(P.S. I could consider putting the whole thing on a dark background to give it a proper boxout look, and allow use of the website syntax highlighting theme.)

**Comment by ge0ffrey** [comment]
No problem, I understand it's not good enough to be merged.
I currently don't have cycles to take this further. Feel free to close this PR (unless someone else is interested in finishing this work).

**Comment by gavinking** [comment]
@ge0ffrey It's not that it's "not good enough", it's just that it needs to adhere to the website style.

**Comment by FroMage** [comment]
Inkscape is actually pretty easy to use.

**Comment by ge0ffrey** [comment]
@gavinking No worries :) I didn't take offense, I agree "not adheres enough" is more accurate ;)

**Comment by FroMage** [comment]
This PR has been closed as a result of moving Ceylon to the Eclipse Foundation, not as a judgement of its value. We are unfortunately unable to restore it ourselves, but if you feel this PR should be reopened, please rebase your work on the current master and create a new PR. Thanks, and sorry for the inconvenience.

**Pull request closed without merging**
