### PR TITLE
Corrected "default" to "formal"

### PR DESCRIPTION
**Pull request by CPColin**

### CODE REVIEW

**Comment by CPColin** [comment]
I don't know how to fix Eclipse's validation problem. I'm fine with somebody just making the edit and discarding my commit.

**Comment by lucaswerkmeister** [comment]
I think the commit message needs a `Signed-off-by` footer. I could amend the commit for you, but that would probably make the lawyers unhappy ;)

```sh
git remote add CPColin https://github.com/CPColin/ceylon-lang.org
git fetch CPColin
git checkout -b patch-1 CPColin/patch-1
git commit --amend --signoff
git push --force-with-lease
```

**Comment by CPColin** [comment]
My part of the contribution is already signed; GitHub did that automatically when I made the change. The problem is that, since I made the edit using GitHub's website, it listed `noreply@github.com` as the committer, with me as the author. Either GitHub needs to start signing its own commits or Eclipse needs to ignore the situation where `noreply@github.com` is the committer, because taking away the ability to use that simple "Edit" button when browsing the code is pretty inconvenient.

I'm not sure whom to target to get either option done, though.

**Comment by lucaswerkmeister** [comment]
This isn’t about cryptographic signatures or the commit metadata – the commit message literally needs to contain the line `Signed-off-by: Colin Bartolome <cbartolo@crappycomic.com>`. (In my personal opinion – yes, it’s very silly. Sorry.)

**Comment by CPColin** [comment]
Yeah, that's extra obnoxious because the error message being given only referred to `noreply@github.com` and when I tried to add the sign-off via GitHub's Edit functionality, it complained that it was invalid. If there's any way this feedback can reach Eclipse, please add my complaint to the pile.

Anyway, it's fixed now.

**Comment by lucaswerkmeister** [comment]
Okay, thanks! Change itself LGTM, probably just a copy+paste from the `default` annotation (which has the same sentence).

**Pull request merged**
