### PR TITLE
Improve tour on dynamic typing.

### PR DESCRIPTION
**Pull request by xkr47**
Add example of runtime checks that are added for dynamically typed expressions. Add examples of property/array index assignment on plain JavaScript objects/arrays including workaround.

### CODE REVIEW

**Comment by FroMage** [comment]
@gavinking review?

**Comment by xkr47** [comment]
Added a paragraph on deleting properties from dynamic objects as well..

**Comment by gavinking** [comment]
@xkr47 Three things I don't like about this patch:

1. This passage:

> For example, if you try to log a message to the console using ... then there will be a runtime check that there indeed is a global object named `console` that has a non-null/undefined value before calling the log method on it.

"if you try to" is not stylistically appropriate. "there will be" is IMO an inappropriate use of tense, and "calling the log method on it" is just clumsy. Much more appropriate would be:

>  For example, this dynamically typed code logs a message to the console: ... The compiler inserts type checks where `console` is evaluated, and where the `log()` method is referenced.

2. You try to introduce two completely separate concepts in a single subsection, and don't even describe one of them in the text, just sticking it into a code example which is already showing something else. Very confusing to the reader.

3. The section that begins "Assignment to properties..." should be in a separate "Gotcha!" section. And the proposed workarounds are quite unreasonable. `eval()` is not a reasonably solution.

**Comment by xkr47** [comment]
Accidentally deleted all my PR branches, sorry for the spam

**Comment by FroMage** [comment]
This PR has been closed as a result of moving Ceylon to the Eclipse Foundation, not as a judgement of its value. We are unfortunately unable to restore it ourselves, but if you feel this PR should be reopened, please rebase your work on the current master and create a new PR. Thanks, and sorry for the inconvenience.

**Pull request closed without merging**
